.MODEL SMALL

.STACK 100H

.DATA
CR EQU 0DH
LF EQU 0AH
MSG1 DB 'Uppercase letter$'
MSG2 DB 'Lowercase letter$'
MSG3 DB 'Number$'
MSG4 DB 'Not an alphanumeric value$'

.CODE

MAIN PROC
MOV AX,@DATA
MOV DS,AX

;FOR INFINITY TEST CASES
INFINITY:

;INPUT
MOV AH,1
INT 21H
MOV BL,AL
;PRINTING NEW LINE
MOV AH,2
MOV DL,CR
INT 21H
MOV AH,2
MOV DL,LF
INT 21H
;CHECKING IF THE CHARECTER IS A UPPERCASE ALPHABET
STEP0:
CMP BX,'A'
JL STEP1
CMP BX,'Z'
JG STEP1
;DSIPALYING CORRESPONDING MESSAGE
LEA DX,MSG1
MOV AH,9 
INT 21H
JMP LAST
;CHECKING IF THE CHARECTER IS A LOWERCASE ALPHABET
STEP1:
CMP BX,'a'
JL STEP2
CMP BX,'z'
JG STEP2 
;DSIPALYING CORRESPONDING MESSAGE
LEA DX,MSG2
MOV AH,9 
INT 21H
JMP LAST
;CHECKING IF THE CHARECTER IS A NUMBER 
STEP2:
CMP BX,'0'
JL STEP3
CMP BX,'9'
JG STEP3
;DSIPALYING CORRESPONDING MESSAGE
LEA DX,MSG3
MOV AH,9 
INT 21H
JMP LAST                         
;CHECKING IF THE CHARECTER IS NOT AN ALPHANUMERIC VALUE
STEP3:
;DSIPALYING CORRESPONDING MESSAGE
LEA DX,MSG4
MOV AH,9 
INT 21H
JMP LAST
;END 
LAST:
;PRINTING NEW LINE
MOV AH,2
MOV DL,CR
INT 21H
MOV AH,2
MOV DL,LF
INT 21H

JMP INFINITY

MAIN ENDP
END MAIN 