.MODEL SMALL

.STACK 100H

.DATA
CR EQU 0DH
LF EQU 0AH
NUM DB ? 
SPACE DB ' $'
MSG DB 'All letters are equal.$'

.CODE

MAIN PROC
MOV AX,@DATA
MOV DS,AX 

;FOR INFINITY TEST CASES
INFINITY:

;TAKING INPUT
MOV AH,1
INT 21H
MOV NUM,AL

;PRINTING SPACE
LEA DX,SPACE
MOV AH,9
INT 21H

;TAKING INPUT
MOV AH,1
INT 21H
MOV BL,AL

;PRINTING SPACE
LEA DX,SPACE
MOV AH,9
INT 21H

;TAKING INPUT
MOV AH,1
INT 21H
MOV BH,AL

;PRINTING NEW LINE
MOV AH,2
MOV DL,CR
INT 21H
MOV AH,2
MOV DL,LF
INT 21H

;INITIALIZING COUNTER REGISTER
MOV CX,'A'

;LOOP
WHILE:
    ;5 POSSIBILITY WHERE THE CHARECTER NUM CAN BRE THE ANSWER
    ;THIS POSSIBILITIES IS FOR NUM
    ;IF THE INPUT SATISFIY ANY OF THESE 5 POSSIBILITIES THAN THE ANSWER WILL BE NUM
    STEP1:
        ;IF NUM == BL AND NUM < BH
        CMP NUM,BL
        JNE STEP2
        CMP NUM,BH
        JGE STEP2
        JMP PRINT
    
    STEP2:
        ;IF NUM == BH AND NUM < BL
        CMP NUM,BH
        JNE STEP3
        CMP NUM,BL
        JGE STEP3
        JMP PRINT
    
    STEP3:
        ;IF BH == BL AND NUM < (BL OR BH)
        CMP BL,BH
        JNE STEP4
        CMP NUM,BL
        JGE STEP4
        JMP PRINT
    
    STEP4:
        ;IF NUM > BL AND NUM < BH
        CMP NUM,BL
        JLE STEP5
        CMP NUM,BH
        JGE STEP5
        JMP PRINT
    
    STEP5: 
        ;IF NUM < BL AND NUM > BH
        CMP NUM,BL
        JGE STEP6
        CMP NUM,BH
        JLE STEP6
        JMP PRINT
    
    STEP6:
    INC CX
    ;THIS PART RUNS THE CODE SEGMENT FOR THE SECOND TIME
    CMP CX,'B'
    JE B
    ;THIS PART RUNS THE CODE SEGMENT FOR THE THIRD TIME 
    CMP CX,'C'
    JE C
    ;THIS IS THE END OF THE LOOP
    JMP OUTOFLOOP
    
    ;EXCHANGING THE VARIABLE AND REGISTERS FOR SECOND ITERATION
    B:
    XCHG NUM,BL
    JMP WHILE
    
    ;EXCHANGING THE VARIABLE AND REGISTERS FOR THIRD ITERATION
    C:
    XCHG NUM,BH 
    JMP WHILE

;IF THE THREE CHARECTER IS EQUAL THEN THIS BLOCK WILL RUN
OUTOFLOOP:
LEA DX,MSG
MOV AH,9
INT 21H
JMP LAST

;IF THERE EXIST AN ANSWER, THIS PART WILL PRINT IT
PRINT:  
MOV DL,NUM
MOV AH,2
INT 21H
JMP LAST

;END OF THE PROGGRAM
LAST:
;PRINITING NEW LINE
MOV AH,2
MOV DL,CR
INT 21H
MOV AH,2
MOV DL,LF
INT 21H

JMP INFINITY

MAIN ENDP
END MAIN